import yfinance as yf
import pandas as pd

# Define the list of ticker symbols for multiple NSE stocks
ticker_symbols = [
   "3MINDIA.NS",
"ACC.NS",
"AIAENG.NS",
"APLAPOLLO.NS",
"AUBANK.NS",
"ABBOTINDIA.NS",
"AWL.NS",
"ABCAPITAL.NS",
"ABFRL.NS",
"AJANTPHARM.NS",
"ALKEM.NS",
"APOLLOTYRE.NS",
"ASHOKLEY.NS",
"ASTRAL.NS",
"AUROPHARMA.NS",
"BSE.NS",
"BALKRISIND.NS",
"BANDHANBNK.NS",
"BANKINDIA.NS",
"MAHABANK.NS",
"BAYERCROP.NS",
"BERGEPAINT.NS",
"BDL.NS",
"BHARATFORG.NS",
"BHARTIHEXA.NS",
"BIOCON.NS",
"CGPOWER.NS",
"CRISIL.NS",
"CARBORUNIV.NS",
"COCHINSHIP.NS",
"COFORGE.NS",
"COLPAL.NS",
"CONCOR.NS",
"COROMANDEL.NS",
"CUMMINSIND.NS",
"DALBHARAT.NS",
"DEEPAKNTR.NS",
"DELHIVERY.NS",
"DIXON.NS",
"EMAMILTD.NS",
"ENDURANCE.NS",
"ESCORTS.NS",
"EXIDEIND.NS",
"NYKAA.NS",
"FEDERALBNK.NS",
"FACT.NS",
"FORTIS.NS",
"GMRAIRPORT.NS",
"GICRE.NS",
"GLAND.NS",
"GLAXO.NS",
"MEDANTA.NS",
"GODREJIND.NS",
"GODREJPROP.NS",
"GRINDWELL.NS",
"FLUOROCHEM.NS",
"GUJGASLTD.NS",
"HDFCAMC.NS",
"HINDPETRO.NS",
"HINDZINC.NS",
"POWERINDIA.NS",
"HONAUT.NS",
"HUDCO.NS",
"IDBI.NS",
"IDFCFIRSTB.NS",
"IRB.NS",
"INDIANB.NS",
"INDHOTEL.NS",
"IOB.NS",
"IREDA.NS",
"IGL.NS",
"INDUSTOWER.NS",
"IPCALAB.NS",
"JKCEMENT.NS",
"JSWINFRA.NS",
"JSL.NS",
"JUBLFOOD.NS",
"KPRMILL.NS",
"KEI.NS",
"KPITTECH.NS",
"KALYANKJIL.NS",
"LTF.NS",
"LTTS.NS",
"LICHSGFIN.NS",
"LINDEINDIA.NS",
"LLOYDSME.NS",
"LUPIN.NS",
"MRF.NS",
"M&MFIN.NS",
"MRPL.NS",
"MANKIND.NS",
"MARICO.NS",
"MFSL.NS",
"MAXHEALTH.NS",
"MAZDOCK.NS",
"METROBRAND.NS",
"MSUMI.NS",
"MPHASIS.NS",
"MUTHOOTFIN.NS",
"NLCINDIA.NS",
"NMDC.NS",
"NAM-INDIA.NS",
"OBEROIRLTY.NS",
"OIL.NS",
"PAYTM.NS",
"OFSS.NS",
"POLICYBZR.NS",
"PIIND.NS",
"PAGEIND.NS",
"PATANJALI.NS",
"PERSISTENT.NS",
"PETRONET.NS",
"PHOENIXLTD.NS",
"POLYCAB.NS",
"POONAWALLA.NS",
"PRESTIGE.NS",
"PGHH.NS",
"RVNL.NS",
"SBICARD.NS",
"SJVN.NS",
"SKFINDIA.NS",
"SRF.NS",
"SCHAEFFLER.NS",
"SOLARINDS.NS",
"SONACOMS.NS",
"STARHEALTH.NS",
"SAIL.NS",
"SUNTV.NS",
"SUNDARMFIN.NS",
"SUNDRMFAST.NS",
"SUPREMEIND.NS",
"SUZLON.NS",
"SYNGENE.NS",
"TATACHEM.NS",
"TATACOMM.NS",
"TATAELXSI.NS",
"TATAINVEST.NS",
"TATATECH.NS",
"NIACL.NS",
"THERMAX.NS",
"TIMKEN.NS",
"TORNTPOWER.NS",
"TIINDIA.NS",
"UNOMINDA.NS",
"UPL.NS",
"UBL.NS",
"IDEA.NS",
"VOLTAS.NS",
"YESBANK.NS",
"ZFCVINDIA.NS"
]

# Initialize a list to store DataFrames
data_frames = []

# Fetch data for each ticker symbol and store the close prices in the list
for ticker in ticker_symbols:
    try:
        data = yf.download(ticker, period="1y")
        close_prices = data[['Close']].rename(columns={'Close': ticker})
        data_frames.append(close_prices)
    except Exception as e:
        print(f"Unable to fetch data for {ticker}: {e}")
        # If unable to fetch data, create a DataFrame with 0 values
        dates = pd.date_range(end=pd.Timestamp.today(), periods=365)
        close_prices = pd.DataFrame({ticker: [0]*365}, index=dates)
        data_frames.append(close_prices)

# Concatenate all DataFrames along the columns
all_close_prices = pd.concat(data_frames, axis=1)

# Save the close prices to an Excel file
all_close_prices.to_excel("NSE_stocks_close_prices.xlsx")

print("Close prices for multiple NSE stocks for the last 1 year have been downloaded and saved to NSE_stocks_close_prices.xlsx")
